<?php
//http://akabia.fr/drupal-7-d%C3%A9veloppement-de-modules
/**
 * Implementation of hook_help().
 */
function helloworld_help($path, $arg) {
  switch ($path) {
    case 'admin/help#helloworld':
      $output = '<h3>helloworld</h3>';
      $output .= '<p>' . t('helloworld', array('@helloworld' => 'http://akabia.fr/drupal-7-d%C3%A9veloppement-de-modules')) . '</p>';
      return $output;
  }
}


/**
* Implementation of hook_permission().
*/
function helloworld_permission() {
  return array(
  'access helloworld' => array('title' => t('Access helloworld'))
  );
}


/**
* Implementation of hook_menu().
*/
function helloworld_menu() {
  $items = array();
   
  $items['helloworld/sayhelloworld'] = array(
  'title' => 'Hello World Test',
  'page callback' => 'say_hello_world',
  'access arguments' => array('access content'),
  'type' => MENU_CALLBACK,
  );
   
  return $items;
}

/**
* affiche helloword dans une page
*/
function say_hello_world() {

  $vars = 'Hello World!';
  return $vars;

}
?>