<?php

/**
 * Implementation of hook_help().
 */
function hello_world_help($path, $arg) {
  switch ($path) {
    case 'admin/help#helloworld':
      $output = '<h3>helloworld</h3>';
      $output .= '<p>' . t('Hello World from <a href="@danlobo" target="_blank">Daniel Lobo</a>', array('@danlobo' => 'https://danlobo.co.uk')) . '</p>';
      return $output;
  }
}


/**
* Implementation of hook_permission().
*/
function hello_world_permission() {
  return array(
  'access hello_world' => array('title' => t('Access Hello World module'))
  );
}


/**
* Implementation of hook_menu().
*/
function hello_world_menu() {
  $items = array();
   
  $items['helloworld'] = array(
  'title' => 'Hello World',
  'page callback' => 'say_hello_world',
  'access arguments' => array('access content'),
  'type' => MENU_CALLBACK,
  );
   
  return $items;
}

/**
 * page callback
 * returns string utilising the Drupal's t() function
 */
function say_hello_world() {

  $text = '<p>' . t('Hello World, by <a href="@danlobo" target="_blank">Daniel Lobo</a>', array('@danlobo' => 'https://danlobo.co.uk')) . '</p>';

  return $text;

}
